---
sudo: false
dist: trusty
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm Gemfile.lock || true
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake $CHECK'
bundler_args: --without system_tests
rvm:
  - 2.4.1
  - 2.1.9
env:
  - PUPPET_GEM_VERSION="~> 4.0" CHECK=spec SPEC_FACTS_OS='redhat-5-x86_64'
  - PUPPET_GEM_VERSION="~> 4.0" CHECK=spec SPEC_FACTS_OS='redhat-6-x86_64'
  - PUPPET_GEM_VERSION="~> 4.0" CHECK=spec SPEC_FACTS_OS='redhat-7-x86_64'
  - PUPPET_GEM_VERSION="~> 4.0" CHECK=spec SPEC_FACTS_OS='centos-5-x86_64'
  - PUPPET_GEM_VERSION="~> 4.0" CHECK=spec SPEC_FACTS_OS='centos-6-x86_64'
  - PUPPET_GEM_VERSION="~> 4.0" CHECK=spec SPEC_FACTS_OS='centos-7-x86_64'
  - PUPPET_GEM_VERSION="~> 4.0" CHECK=spec SPEC_FACTS_OS='oraclelinux-6-x86_64'
  - PUPPET_GEM_VERSION="~> 4.0" CHECK=spec SPEC_FACTS_OS='oraclelinux-7-x86_64'
  - PUPPET_GEM_VERSION="~> 4.0" CHECK=spec SPEC_FACTS_OS='scientific-5-x86_64'
  - PUPPET_GEM_VERSION="~> 4.0" CHECK=spec SPEC_FACTS_OS='scientific-6-x86_64'
  - PUPPET_GEM_VERSION="~> 4.0" CHECK=spec SPEC_FACTS_OS='scientific-7-x86_64'
  - PUPPET_GEM_VERSION="~> 4.0" CHECK=spec SPEC_FACTS_OS='debian-7-x86_64'
  - PUPPET_GEM_VERSION="~> 4.0" CHECK=spec SPEC_FACTS_OS='debian-8-x86_64'
  - PUPPET_GEM_VERSION="~> 4.0" CHECK=spec SPEC_FACTS_OS='ubuntu-14.04-x86_64'
  - PUPPET_GEM_VERSION="~> 4.0" CHECK=spec SPEC_FACTS_OS='ubuntu-16.04-x86_64'

matrix:
  fast_finish: true
  include:
    - env: CHECK=rubocop
    - env: CHECK="syntax lint"
    - env: CHECK=metadata_lint
branches:
  only:
    - master
    - /^v\d/
notifications:
  email: false
deploy:
  provider: puppetforge
  user: puppet
  password:
    secure: ""
  on:
    tags: true
    all_branches: true
    condition: "$DEPLOY_TO_FORGE = yes"
